#apiVersion: v1
#kind: Namespace
#metadata:
#  name: collaboration-tools
#---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    account: photoprism
  name: photoprism
  namespace: collaboration-tools
---
# Source: photoprism/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: photoprism
  namespace: collaboration-tools
  labels:
    app.kubernetes.io/instance: photoprism
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: photoprism
    app.kubernetes.io/version: 220629-jammy
    helm.sh/chart: photoprism-7.1.2
    expose: "true"
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 2342
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: photoprism
    app.kubernetes.io/instance: photoprism
---
# Source: photoprism/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
  namespace: collaboration-tools
  labels:
    app.kubernetes.io/instance: photoprism
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: photoprism
    app.kubernetes.io/version: 220629-jammy
    helm.sh/chart: photoprism-7.1.2
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: photoprism
      app.kubernetes.io/instance: photoprism
  template:
    metadata:
      labels:
        app.kubernetes.io/name: photoprism
        app.kubernetes.io/instance: photoprism
    spec:
      serviceAccountName: photoprism
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: photoprism
          image: "photoprism/photoprism:220629-jammy"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          imagePullPolicy: IfNotPresent
          env:
            - name: GID
              value: null
            - name: PHOTOPRISM_ADMIN_PASSWORD
              value: photo-test
            - name: PHOTOPRISM_DATABASE_DRIVER
              value: sqlite
            - name: PHOTOPRISM_DATABASE_NAME
              value: photoprism
            - name: PHOTOPRISM_DATABASE_PASSWORD
              value: photoprism
            - name: PHOTOPRISM_DATABASE_SERVER
              value: photoprism-mariadb:3306
            - name: PHOTOPRISM_DATABASE_USER
              value: photoprism
            - name: PHOTOPRISM_ORIGINALS_PATH
              value: /photoprism/originals
            - name: PHOTOPRISM_PUBLIC
              value: "false"
            - name: PHOTOPRISM_STORAGE_PATH
              value: /photoprism/storage
            - name: TZ
              value: UTC
            - name: UID
              value: null
            - name: UMASK
              value: null
          ports:
            - name: http
              containerPort: 2342
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 2342
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 2342
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 2342
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
