apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wave-6-aoa
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/civo-kapoozi/
    targetRevision: HEAD
    path: environment/wave-6/prod/active/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true